Repository voxel51/platform-sdk, pull requests merged in 2020-02, with the labels that each got.

#24 More robust handling of failures
  examples/platform-demo/main.bash
  pylintrc
  quickstarts/PLATFORM.md
  voxel51/platform/config.py
  voxel51/platform/task.py
Labels: enhancement

#26 Jit urls reverse compatibility
  voxel51/platform/api.py
  voxel51/platform/task.py
Labels: enhancement

#27 Fix logos
  README.md
  quickstarts/IMAGE_TO_VIDEO.md
  quickstarts/PLATFORM.md
Labels: documentation

#25 Generate signed URLs on-demand
  README.md
  tests/.gitignore
  tests/platform/README.md
  tests/platform/server/config.js
  tests/platform/server/index.js
  tests/platform/server/server.js
  voxel51/platform/api.py
  voxel51/platform/task.py
Labels: enhancement

#29 Updating TaskStatus to store times as `datetime`s
  voxel51/platform/task.py
Labels: enhancement

#31 Fix api-py installation instructions
  README.md
Labels: bug, documentation

#32 test-i2v: Ensure that output directory exists before running
  tests/image2video/test-i2v
Labels: bug
